KNOWN_PROTOCOL_IDENTIFIERS = {
    "ASCRIBE": "Ascribe",
    "BITPROOF": "BitProof",
    "BS": "Blocksign",
    "CC": "Colu",
    "CryptoProof-": "CryptoCopyright",
    "CryptoTests-": "CryptoCopyright",
    "DOCPROOF": "Proof of Existence",
    "EW": "Eternity Wall",
    "FA": "Factom",
    "FACTOM00": "Factom",
    "Fa": "Factom",
    "Factom!!": "Factom",
    "LaPrevue": "LaPrevue",
    "MG": "MoneGraph",
    "OA": "OpenAssets",
    "ORIGMY": "OriginalMy",
    "ProveBit": "ProveBit",
    "RMBd": "Remembr",
    "RMDe": "Remembr",
    "S1": "Stampery",
    "S2": "Stampery",
    "S3": "Stampery",
    "S4": "Stampery",
    "S5": "Stampery",
    "SB.D": "Smart Bit",
    "SPK": "CoinSpark",
    "STAMPD##": "Stampd",
    "UNicDC": "Nicosai",
    "omni": "Omni",
}
